admin_index:
    path:     /
    defaults: { _controller: "BshdevBundle:Admin:index" }
    methods:  GET

admin_show:
    path:     /{id}/show
    defaults: { _controller: "BshdevBundle:Admin:show" }
    methods:  GET

admin_new:
    path:     /new
    defaults: { _controller: "BshdevBundle:Admin:new" }
    methods:  [GET, POST]

admin_editContact:
    path:     /{id}/Contact
    defaults: { _controller: "BshdevBundle:Admin:editContact" }
    methods:  [GET, POST]

admin_editHomepage:
    path:     /{id}/Homepage
    defaults: { _controller: "BshdevBundle:Admin:editHomepage" }
    methods:  [GET, POST]

admin_editHistory:
    path:     /{id}/History
    defaults: { _controller: "BshdevBundle:Admin:editHistory" }
    methods:  [GET, POST]

admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "BshdevBundle:Admin:delete" }
    methods:  DELETE
