career_index:
    path:     /
    defaults: { _controller: "BshdevBundle:Career:index" }
    methods:  GET

career_show:
    path:     /{id}/show
    defaults: { _controller: "BshdevBundle:Career:show" }
    methods:  GET

career_new:
    path:     /new
    defaults: { _controller: "BshdevBundle:Career:new" }
    methods:  [GET, POST]

career_edit:
    path:     /{id}/edit
    defaults: { _controller: "BshdevBundle:Career:edit" }
    methods:  [GET, POST]

career_delete:
    path:     /{id}/delete
    defaults: { _controller: "BshdevBundle:Career:delete" }
    methods:  DELETE
