job_index:
    path:     /
    defaults: { _controller: "BshdevBundle:Job:index" }
    methods:  GET

job_show:
    path:     /{id}/show
    defaults: { _controller: "BshdevBundle:Job:show" }
    methods:  GET

job_new:
    path:     /new
    defaults: { _controller: "BshdevBundle:Job:new" }
    methods:  [GET, POST]

job_edit:
    path:     /{id}/edit
    defaults: { _controller: "BshdevBundle:Job:edit" }
    methods:  [GET, POST]

job_delete:
    path:     /{id}/delete
    defaults: { _controller: "BshdevBundle:Job:delete" }
    methods:  DELETE
