bshdev_person:
    resource: "@BshdevBundle/Resources/config/routing/person.yml"
    prefix:   /person

bshdev_job:
    resource: "@BshdevBundle/Resources/config/routing/job.yml"
    prefix:   /job

bshdev_home:
    path:     /
    defaults: { _controller: BshdevBundle:Default:home }

bshdev_contact:
    path:     /contact
    defaults: { _controller: BshdevBundle:Default:contact }

bshdev_references:
    path:     /references
    defaults: { _controller: BshdevBundle:Default:references }

bshdev_history:
    path:     /history
    defaults: { _controller: BshdevBundle:Default:history }

person_candidature:
    path:     /candidature/{id}
    defaults: { _controller: "BshdevBundle:Person:candidature" }
    methods:  [GET, POST]

person_spontaCandidature:
    path:     /spontaCandidature
    defaults: { _controller: "BshdevBundle:Person:spontaCandidature" }
    methods:  [GET, POST]