bshdev_person:
    resource: "@BshdevBundle/Resources/config/routing/person.yml"
    prefix:   /person

bshdev_job:
    resource: "@BshdevBundle/Resources/config/routing/job.yml"
    prefix:   /job

bshdev_index:
    path:     /index
    defaults: { _controller: BshdevBundle:Default:index }

bshdev_home:
    path:     /
    defaults: { _controller: BshdevBundle:Default:home }

person_candidature:
    path:     /candidature/{id}
    defaults: { _controller: "BshdevBundle:Person:candidature" }
    methods:  [GET, POST]

person_spontaCandidature:
    path:     /spontaCandidature
    defaults: { _controller: "BshdevBundle:Person:spontaCandidature" }
    methods:  [GET, POST]