BshdevBundle\Entity\Person:
    type: entity
    table: null
    repositoryClass: BshdevBundle\Repository\PersonRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        address:
            type: string
            length: 255
        cp:
            type: string
            length: 255
        town:
            type: string
            length: 255
        email:
            type: string
            length: 255
        phone:
            type: string
            length: 255
        language:
            type: string
            length: 255
        imageCv:
            type: string
            lenght: 255
        imageIdentity:
            type: string
            lenght: 255


    manyToOne:
        job:
            targetEntity: BshdevBundle\Entity\Job
            inversedBy: id

    lifecycleCallbacks:
      prePersist: [ preUploadCv, preUploadIdentity  ]
      preUpdate: [ preUploadCv, preUploadIdentity ]
      postPersist: [ uploadCv, uploadIdentity ]
      postUpdate: [ uploadCv, uploadIdentity ]
      postRemove: [ removeUploadCv, removeUploadIdentity ]